/* Prototype copy dictionary. Terminology authority: _task/system-design/spec/核心认知.md §2. */
(function (root) {
  const words = {
  en: {
    flipToBack: 'Flip card', flipToFront: 'Back to front',
    viewChainRecord: 'View chain record', hideChainRecord: 'Hide chain record',
    viewFullProfile: 'View full profile', hideFullProfile: 'Hide full profile',
    connect: 'Connect Wallet', connected: 'Connected', notConnected: 'Not connected', connecting: 'Connecting', disconnect: 'Disconnect', accountSwitch: 'Switch account', wallet: 'Wallet',
    myIdentity: 'My Identity', publicIdentity: 'Public Identity', preferences: 'Preferences', theme: 'Theme', light: 'Light', dark: 'Dark', language: 'Language',
    headlineOne: 'Own your identity.', headlineTwo: 'Own your words.', welcomeIntro: 'A place to stand. A voice that belongs to you.', welcomeBody: 'Start with your wallet. Your identity and your words stay yours.',
    welcomeNote: 'Your wallet controls your identity.', horizonCaption: 'A foundation for your voice', domeLabel: 'Play the seven sky lines',
    walletNote: 'Yours Wallet', independent: 'Your identity starts with you.', footer: 'Your wallet. Your identity. Your words.', prototype: 'Interactive prototype', scenarios: 'Explore scenarios', close: 'Close',
    scenario: 'Wallet identity', new: 'New identity', existing: 'Published identity', incomplete: 'Incomplete profile', resolveFail: 'Resolution fails', missing: 'Wallet unavailable',
    simulatorNote: 'Demo only. No wallet connection, signature or transaction is sent.', simulatorHint: 'Choose an identity scenario, then connect or resolve again.',
    sampleDataNote: 'Identity and chain records are sample data. Authorization dialogs represent the external wallet.', walletAuthorization: 'Yours Wallet · External authorization',
    nextResult: 'Next operation result', resultSuccess: 'Success', nextResultHint: 'Applies once after approving a connection, creation or update. Cancelling keeps this setting.',
    accountEvent: 'Next account event', none: 'No event', 'switch-confirm': 'Switch during authorization', 'switch-process': 'Switch during processing', 'disconnect-confirm': 'Disconnect during authorization', 'disconnect-process': 'Disconnect during processing',
    accountEventHint: 'Runs once on create or update: after 1.2s in authorization, or 0.6s in processing.',
    resolveAgain: 'Resolve again', failClipboard: 'Simulate copy failure', reset: 'Reset session',
    connectTitle: 'Connect Yours Wallet', connectBody: 'Let this app see your wallet identity. Publishing needs a separate confirmation.', approve: 'Approve', cancel: 'Cancel', simulateFailure: 'Simulate failure',
    connectCancelled: 'Connection cancelled', connectFailed: 'Connection failed', connectFailedBody: 'Your identity is unchanged. Check your wallet and try again.',
    missingTitle: 'Yours Wallet is unavailable', missingBody: 'No supported wallet was found. Open Yours Wallet, then try again.', retry: 'Try Again',
    resolving: 'Resolving your identity...', resolvingBody: 'Checking whether your wallet has a published identity.', resolveFailed: "Couldn't resolve identity", resolveFailedBody: 'Try again, or disconnect and switch to another account.',
    setup: 'Identity Setup', setupHeading: 'Make it yours.', setupBody: 'Choose how your identity appears to the world.', complete: 'Complete your profile', completeBody: 'Already published. Add the missing profile details to continue.',
    avatar: 'Avatar', chooseImage: 'Choose image', removeImage: 'Remove image', imageHint: 'Local PNG, JPEG or WebP. Optional.', invalidImage: 'Choose a valid PNG, JPEG or WebP image.', name: 'Name', required: 'Enter a name.', nameLong: 'Use 100 characters or fewer.', bioLong: 'Use 1000 characters or fewer.', typeRequired: 'Choose Person or Organization.',
    type: 'Type', Person: 'Person', Organization: 'Organization', bio: 'Bio', optional: 'Optional', review: 'Review', noChanges: 'No changes', back: 'Back', profile: 'Profile', editProfile: 'Edit Profile', editHeading: 'A little more you.', editBody: 'Update how you appear. Your BAP ID stays the same.',
    reviewHeading: 'This is your identity.', reviewBody: 'Review the details before confirming in your wallet.', create: 'Create Identity', createImpact: 'Your identity and profile will become public.', saveImpact: 'Your updated profile will become public. Your BAP ID will not change.', localId: 'Locally computed · not yet published', published: 'Published', controlStatement: 'Your wallet controls this identity.',
    copy: 'Copy', copied: 'Copied', copyFailed: "Couldn't copy", copyBap: 'Copy full BAP ID', noBio: 'No bio yet.',
    createTitle: 'Confirm identity creation', saveTitle: 'Confirm profile update', currentIdentity: 'Current identity',
    creating: 'Creating identity...', saving: 'Saving...', processingBody: 'Waiting for the wallet. Disconnecting or switching account cancels this operation.',
    createCancelled: 'Creation cancelled', saveCancelled: 'Saving cancelled', retained: 'Your draft is kept.',
    createFailed: "Couldn't create identity", saveFailed: "Couldn't save profile", operationFailedBody: 'The operation did not complete. Your values are kept. Try again.',
    ready: 'Your identity is ready', readyBody: 'You now have a place to stand. Your wallet remains in control.', goIdentity: 'Go to My Identity', saved: 'Saved',
    identityIntro: 'A constant in a changing world.', identityBody: 'Your public identity, under your control.', owner: 'Controlled by your connected wallet', profileDetails: 'Profile details', account: 'Wallet account',
    publicIntro: 'Your identity, in the open.', publicBody: 'A public view of the identity you control.', backIdentity: 'Back to My Identity', ownedByYou: 'Identity, owned by you.',
    save: 'Save Changes', discardTitle: 'Discard unsaved changes?', discardBody: 'Changes are not saved. Keep editing, or discard them to leave.', keepEditing: 'Keep editing', discard: 'Discard changes',
    accountChanged: 'Account changed. Pending operations were cancelled.', identityUnchanged: 'Your identity is unchanged.', current: 'Current', preferenceHint: 'Language and appearance stay on this device.',
    setupStep: 'Profile', reviewStep: 'Review', confirmStep: 'Confirm', doneStep: 'Ready', copyFailureOn: 'Copy failure simulation is on', privatePreview: 'Public view preview',
    walletStatus: 'Wallet status', persistFailed: 'Preferences could not be saved on this device.',
    chainRecord: 'Chain record', identityPublication: 'Identity publication', blockHeight: 'Block height', confirmation: 'Confirmation', confirmed: 'Confirmed', pendingConfirmation: 'Awaiting block confirmation', pendingBlock: 'Awaiting block', publicationTx: 'Publication TxID', copyTx: 'Copy publication TxID', recordUnavailable: 'Transaction record unavailable'
  },
  zh: {
    flipToBack: '翻面', flipToFront: '翻回正面',
    viewChainRecord: '查看链上记录', hideChainRecord: '收起链上记录',
    viewFullProfile: '查看完整资料', hideFullProfile: '收起完整资料',
    connect: '连接钱包', connected: '已连接', notConnected: '未连接', connecting: '正在连接', disconnect: '断开连接', accountSwitch: '切换账户', wallet: '钱包',
    myIdentity: '我的身份', publicIdentity: '公开身份', preferences: '偏好设置', theme: '主题', light: '浅色', dark: '深色', language: '语言',
    headlineOne: '拥有你的身份。', headlineTwo: '拥有你的话语。', welcomeIntro: '立于自己的坐标，发出自己的声音。', welcomeBody: '从钱包开始。身份与话语，都由你掌控。',
    welcomeNote: '你的钱包掌控你的身份。', horizonCaption: '让话语有所立足', domeLabel: '拨动七条天幕线',
    walletNote: 'Yours Wallet', independent: '身份，由你开始。', footer: '你的钱包。你的身份。你的话语。', prototype: '交互原型', scenarios: '演练场景', close: '关闭',
    scenario: '钱包身份场景', new: '新身份', existing: '已发布身份', incomplete: '资料不完整', resolveFail: '解析失败', missing: '钱包不可用',
    simulatorNote: '仅作演示。不会连接钱包、签名或发送交易。', simulatorHint: '选择身份场景后，连接钱包或重新解析。',
    sampleDataNote: '身份与链上记录均为示例数据。授权弹窗代表外部钱包界面。', walletAuthorization: 'Yours Wallet · 外部钱包授权',
    nextResult: '下一次操作结果', resultSuccess: '成功', nextResultHint: '批准连接、创建或更新后生效一次；取消授权会保留此设置。',
    accountEvent: '下一次账户变化', none: '不触发', 'switch-confirm': '授权时切换账户', 'switch-process': '处理中切换账户', 'disconnect-confirm': '授权时断开连接', 'disconnect-process': '处理中断开连接',
    accountEventHint: '创建身份或更新资料时触发一次：授权开始 1.2 秒后，或处理开始 0.6 秒后。',
    resolveAgain: '重新解析', failClipboard: '模拟复制失败', reset: '重置会话',
    connectTitle: '连接 Yours Wallet', connectBody: '允许应用查看钱包身份；发布时另行确认。', approve: '批准', cancel: '取消', simulateFailure: '模拟失败',
    connectCancelled: '连接已取消', connectFailed: '连接失败', connectFailedBody: '身份未改变。请检查钱包后重试。',
    missingTitle: 'Yours Wallet 不可用', missingBody: '未发现支持的钱包。请打开 Yours Wallet 后重试。', retry: '重试',
    resolving: '正在解析身份…', resolvingBody: '正在查询当前钱包是否已有公开身份。', resolveFailed: '无法解析身份', resolveFailedBody: '可重试，或断开后切换其他账户。',
    setup: '设置身份', setupHeading: '让身份属于你。', setupBody: '选择你向世界展示自己的方式。', complete: '完善你的资料', completeBody: '身份已发布。补全资料后继续。',
    avatar: '头像', chooseImage: '选择图片', removeImage: '移除图片', imageHint: '本地 PNG、JPEG 或 WebP，可选。', invalidImage: '请选择有效的 PNG、JPEG 或 WebP 图片。', name: '名称', required: '请输入名称。', nameLong: '名称不能超过 100 个字符。', bioLong: '简介不能超过 1000 个字符。', typeRequired: '请选择个人或组织。',
    type: '类型', Person: '个人', Organization: '组织', bio: '简介', optional: '可选', review: '预览确认', noChanges: '暂无修改', back: '返回', profile: '资料', editProfile: '编辑资料', editHeading: '更真实地表达你。', editBody: '更新展示资料，BAP ID 保持不变。',
    reviewHeading: '这就是你的身份。', reviewBody: '核对资料后，在钱包中确认。', create: '创建身份', createImpact: '你的身份和资料将公开发布。', saveImpact: '更新后的资料将公开发布，BAP ID 保持不变。', localId: '已本地计算 · 尚未发布', published: '已发布', controlStatement: '你的钱包掌控此身份。',
    copy: '复制', copied: '已复制', copyFailed: '无法复制', copyBap: '复制完整 BAP ID', noBio: '尚未填写简介。',
    createTitle: '确认创建身份', saveTitle: '确认更新资料', currentIdentity: '当前身份',
    creating: '正在创建身份…', saving: '正在保存…', processingBody: '正在等待钱包返回。断开或切换账户会取消此操作。',
    createCancelled: '创建已取消', saveCancelled: '保存已取消', retained: '填写内容已保留。',
    createFailed: '无法创建身份', saveFailed: '无法保存资料', operationFailedBody: '操作未完成，已保留填写内容。请重试。',
    ready: '你的身份已就绪', readyBody: '现在，你有了自己的坐标。钱包始终由你掌控。', goIdentity: '前往我的身份', saved: '已保存',
    identityIntro: '变化之中，自有坐标。', identityBody: '你的公开身份，由你掌控。', owner: '由当前连接的钱包控制', profileDetails: '资料详情', account: '钱包账户',
    publicIntro: '让世界看到你。', publicBody: '查看你所掌控身份的公开展示。', backIdentity: '返回我的身份', ownedByYou: '身份，属于你。',
    save: '保存修改', discardTitle: '放弃未保存的修改？', discardBody: '修改未保存。继续编辑，或放弃后离开。', keepEditing: '继续编辑', discard: '放弃修改',
    accountChanged: '账户已切换，进行中的操作已取消。', identityUnchanged: '身份未改变。', current: '当前', preferenceHint: '语言与主题偏好保存在此设备。',
    setupStep: '资料', reviewStep: '核对', confirmStep: '确认', doneStep: '就绪', copyFailureOn: '已开启复制失败模拟', privatePreview: '公开展示预览',
    walletStatus: '钱包状态', persistFailed: '无法在此设备保存偏好。',
    chainRecord: '链上记录', identityPublication: '身份发布记录', blockHeight: '区块高度', confirmation: '确认状态', confirmed: '已确认', pendingConfirmation: '等待区块确认', pendingBlock: '等待入块', publicationTx: '发布交易 TxID', copyTx: '复制发布交易 TxID', recordUnavailable: '暂无交易记录'
  }
  };
  Object.assign(words.en, {"myContent": "My content", "contentEyebrow": "WORDS & IDENTITY", "contentIntro": "A place for drafts. A record of your published words.", "contentNew": "New draft", "contentWritingAs": "Writing as", "contentDrafts": "Drafts", "contentPublished": "Published", "contentDraft": "Draft", "contentPublishedOne": "Published", "contentFilter": "Content filter", "contentContinue": "Continue writing", "contentRead": "Read", "contentUntitled": "Untitled", "contentStartWriting": "Start with a thought.", "contentLoading": "Loading your words…", "contentLoadFailed": "Couldn’t load your content", "contentLoadFailedBody": "Your saved words are unchanged. Try again.", "contentEmptyDrafts": "A blank page, a new beginning.", "contentEmptyDraftsBody": "Start a draft. Your words can take their time.", "contentEmptyPublished": "Your first publication starts here.", "contentEmptyPublishedBody": "When you publish, your words will appear here.", "contentLocalNote": "Drafts stay in this browser until you publish.", "contentBack": "My content", "contentMissing": "Content not found", "contentGateTitle": "Your words begin with your identity.", "contentGateBody": "Connect your wallet and prepare your identity to open your drafts. Public writing is always readable.", "contentReadSample": "Read a sample", "contentScenarios": "Content scenarios", "contentListScenario": "Content list", "contentScenario-normal": "Normal", "contentScenario-empty": "Empty", "contentScenario-failure": "Load failure"});
  Object.assign(words.zh, {"myContent": "我的内容", "contentEyebrow": "文字与身份", "contentIntro": "留住想法，整理草稿，查看每一次发布。", "contentNew": "新建草稿", "contentWritingAs": "当前写作身份", "contentDrafts": "草稿", "contentPublished": "已发布", "contentDraft": "草稿", "contentPublishedOne": "已发布", "contentFilter": "内容筛选", "contentContinue": "继续写作", "contentRead": "阅读", "contentUntitled": "未命名内容", "contentStartWriting": "从一个想法开始。", "contentLoading": "正在载入内容…", "contentLoadFailed": "暂时无法载入内容", "contentLoadFailedBody": "已保存的内容没有改变，请重试。", "contentEmptyDrafts": "新的一页，新的想法。", "contentEmptyDraftsBody": "先写下来，慢慢整理。", "contentEmptyPublished": "第一篇内容，从这里开始。", "contentEmptyPublishedBody": "发布成功后，你的文字将显示在这里。", "contentLocalNote": "草稿保存在当前浏览器，发布前仅你可见。", "contentBack": "我的内容", "contentMissing": "未找到此内容", "contentGateTitle": "用你的身份，写下你的文字。", "contentGateBody": "连接钱包并准备好身份后，即可打开草稿。公开文章无需连接钱包即可阅读。", "contentReadSample": "阅读示例", "contentScenarios": "内容场景", "contentListScenario": "内容列表", "contentScenario-normal": "正常", "contentScenario-empty": "空内容", "contentScenario-failure": "加载失败"});
  Object.assign(words.en, {"editorSource": "Markdown source", "editorFormatting": "Text formatting", "editorHeading": "Heading", "editorPlaceholder": "text", "editorMore": "More", "editorMode": "Editor view", "editorCharacters": "characters", "editorBytes": "bytes", "editorUtf8": "Markdown · UTF-8", "editorTooLong": "This draft exceeds the prototype limit of 100 KiB. Shorten it before reviewing. Your text is kept.", "editor-bold": "Bold", "editor-italic": "Italic", "editor-link": "Link", "editor-strike": "Strikethrough", "editor-quote": "Quote", "editor-unordered": "Bullet list", "editor-ordered": "Numbered list", "editor-task": "Task list", "editor-code": "Inline code", "editor-codeblock": "Code block", "editor-table": "Table", "editor-rule": "Divider", "editor-undo": "Undo", "editor-redo": "Redo", "editor-find": "Find", "editor-edit": "Write", "editor-split": "Split view", "editor-preview": "Preview"});
  Object.assign(words.zh, {"editorSource": "Markdown 源码", "editorFormatting": "文字格式", "editorHeading": "标题", "editorPlaceholder": "文字", "editorMore": "更多", "editorMode": "编辑器视图", "editorCharacters": "字", "editorBytes": "字节", "editorUtf8": "Markdown · UTF-8", "editorTooLong": "正文超过原型的 100 KiB 上限，请缩短后检查发布。全文已保留。", "editor-bold": "粗体", "editor-italic": "斜体", "editor-link": "链接", "editor-strike": "删除线", "editor-quote": "引用", "editor-unordered": "无序列表", "editor-ordered": "有序列表", "editor-task": "任务列表", "editor-code": "行内代码", "editor-codeblock": "代码块", "editor-table": "表格", "editor-rule": "分隔线", "editor-undo": "撤销", "editor-redo": "重做", "editor-find": "查找", "editor-edit": "编辑", "editor-split": "双栏", "editor-preview": "预览"});
  Object.assign(words.en, {"markdownUnsupported": "This text includes syntax outside the supported set. It is shown as text; no media is loaded."});
  Object.assign(words.zh, {"markdownUnsupported": "正文包含暂不支持的语法，已按文字展示，不加载媒体。"});
  Object.assign(words.en, {"draft-saving": "Saving…", "draft-saved": "Saved in this browser", "draft-error": "Not saved", "draftSaveFailedBody": "Your latest words are still on this page. Storage is unavailable. Keep this page open and try again.", "draftReadFailed": "Saved drafts could not be read. Existing storage has not been replaced. Try again when storage is available.", "draftDelete": "Delete draft", "draftDeleteTitle": "Delete this draft?", "draftDeleteBody": "This removes only the local draft from this browser. Published versions remain unchanged.", "draftLeaveTitle": "Keep your latest words?", "draftLeaveBody": "Some changes have not been saved. Choose how to leave this draft.", "draftSaveLeave": "Save and leave", "draftDiscardLeave": "Discard unsaved changes", "draftDeleted": "Draft deleted.", "draftDeleteFailed": "The draft could not be deleted. It is still available.", "draftStorageScenario": "Draft storage", "draftStorageFailure": "Storage write fails"});
  Object.assign(words.zh, {"draft-saving": "保存中…", "draft-saved": "已保存到此浏览器", "draft-error": "尚未保存", "draftSaveFailedBody": "最新正文仍保留在页面中。暂时无法写入存储，请保持页面打开并重试。", "draftReadFailed": "无法读取已保存的草稿，原有存储未被覆盖。请在存储恢复后重试。", "draftDelete": "删除草稿", "draftDeleteTitle": "删除这份草稿？", "draftDeleteBody": "此操作仅移除当前浏览器中的草稿，不影响已发布版本。", "draftLeaveTitle": "保留最新修改？", "draftLeaveBody": "部分修改尚未保存，请选择如何离开这份草稿。", "draftSaveLeave": "保存并离开", "draftDiscardLeave": "放弃未保存修改", "draftDeleted": "草稿已删除。", "draftDeleteFailed": "草稿未能删除，内容仍保留。", "draftStorageScenario": "草稿存储", "draftStorageFailure": "存储写入失败"});
  Object.assign(words.en, {"markdownImport": "Import .md", "markdownExport": "Export .md", "importType": "Choose a Markdown (.md) file. Your draft is unchanged.", "importSize": "This file exceeds 100 KiB. Your draft is unchanged.", "importEncoding": "This file is not valid UTF-8. Your draft is unchanged.", "importReadError": "Could not read this file. Please try again.", "importReplaceTitle": "Replace this draft?", "importReplaceBody": "The imported Markdown will replace the current text. Export a copy first if you want to keep it.", "importReplace": "Replace text"});
  Object.assign(words.zh, {"markdownImport": "导入 .md", "markdownExport": "导出 .md", "importType": "请选择 Markdown（.md）文件，当前正文未改变。", "importSize": "文件超过 100 KiB，当前正文未改变。", "importEncoding": "文件不是有效的 UTF-8 编码，当前正文未改变。", "importReadError": "文件读取失败，请重试。", "importReplaceTitle": "替换当前草稿？", "importReplaceBody": "导入的 Markdown 将替换当前正文。如需保留，请先导出一份副本。", "importReplace": "替换正文"});
  Object.assign(words.en, {"contentReview": "Review publication", "reviewEyebrow": "Before your words go public", "reviewIntro": "Read it once more. This exact text will carry your identity.", "reviewExpired": "Review this draft again before signing. The text or identity has changed, or this review has expired.", "reviewEmpty": "Write something before publishing.", "reviewImpactTitle": "A public, lasting record", "reviewImpact": "Your text and author identity will be public. Published words cannot be overwritten. Changes create a new version; earlier versions remain readable.", "reviewEdit": "Back to editing", "contentSignPublish": "Sign and publish"});
  Object.assign(words.zh, {"contentReview": "检查发布", "reviewEyebrow": "发布之前", "reviewIntro": "再读一遍。这份正文将以你的身份签名发布。", "reviewExpired": "正文或身份已变化，或本次确认已失效。请回到草稿重新检查发布。", "reviewEmpty": "正文为空，请先写下一些内容。", "reviewImpactTitle": "公开且保留的记录", "reviewImpact": "正文和作者身份将公开。发布后不能覆盖原文；修改会追加新版本，旧版本仍可阅读。", "reviewEdit": "返回修改", "contentSignPublish": "签名并发布"});
  Object.assign(words.en, {"publishEyebrow": "Your words, your identity", "publish-authorize": "Ready for your signature", "publish-signing": "Signing your words", "publish-broadcasting": "Publishing your words", "publish-published": "Your words are published", "publish-unknown": "Publication needs checking", "publish-failed": "Publication did not complete", "publish-cancelled": "Signature cancelled", "publishCancelled": "Signature cancelled. Your draft is kept.", "publishSignatureStep": "Identity signature", "publishChainStep": "Publish on chain", "publishSigned": "Signature step complete", "publishSignDescription": "Authorize this identity and this exact text.", "publishChainDescription": "A signature is complete only for this step; publication has its own result.", "publishAccepted": "Accepted and recorded", "publishProcessing": "Keep this page open while this step completes.", "publishStorage": "The publication record could not be saved. Your draft and operation are kept. Restore storage, then check the result.", "publishNotReceived": "The query confirms this publication was not received. Review again before retrying.", "publishStillUnknown": "The result is still unknown. Check again later.", "publishSignFailed": "Identity signing failed. No publication was submitted.", "publishBroadcastFailed": "Publication was rejected after signing. Your draft is kept.", "publishUnknownBody": "This operation may have been received. Check its result before publishing again; the original text and identity are retained.", "publishDraftKept": "Your words are still in your draft. Review the text and identity before trying again.", "publishSampleRecord": "Publication record · sample", "publishSampleTx": "Sample TxID", "publishSimulation": "Prototype simulation: no real signature, transaction or fee is created.", "publishQuery": "Check result", "publishReviewAgain": "Return to draft and review", "publishAuthorizeTitle": "Authorize identity signing", "publishSampleWallet": "Simulated wallet", "publishAuthorizeBody": "Sign the Markdown you just reviewed with the following identity, then publish it.", "publishAuthorize": "Authorize signing", "scenario-publish": "Publication outcome", "scenario-query": "Unknown-result query", "scenario-confirmation": "Chain confirmation", "scenario-account": "Account change during publication", "scenario-success": "Success", "scenario-sign-failed": "Signature failure", "scenario-broadcast-failed": "Publication rejected", "scenario-unknown": "Result unknown", "scenario-accepted": "Accepted", "scenario-not-received": "Definitely not received", "scenario-pending": "Pending confirmation", "scenario-confirmed": "Confirmed", "scenario-none": "No change", "scenario-broadcasting-switch": "Switch during publication", "scenario-broadcasting-disconnect": "Disconnect during publication"});
  Object.assign(words.zh, {"publishEyebrow": "你的文字，你的身份", "publish-authorize": "等待身份签名授权", "publish-signing": "正在签名", "publish-broadcasting": "正在发布", "publish-published": "内容已发布", "publish-unknown": "结果待核实", "publish-failed": "发布未完成", "publish-cancelled": "签名已取消", "publishCancelled": "签名已取消，草稿已保留。", "publishSignatureStep": "身份签名", "publishChainStep": "链上发布", "publishSigned": "签名步骤已完成", "publishSignDescription": "授权当前身份与本次正文。", "publishChainDescription": "签名完成后继续发布，发布结果单独确认。", "publishAccepted": "已接收并保存发布记录", "publishProcessing": "正在处理，请稍候。", "publishStorage": "发布记录暂时无法保存，草稿与操作快照仍保留。请恢复存储后查询结果。", "publishNotReceived": "查询结果明确未接收。请重新检查正文后再发布。", "publishStillUnknown": "结果仍待核实，请稍后再次查询。", "publishSignFailed": "身份签名失败，尚未提交发布。", "publishBroadcastFailed": "签名完成，但发布被拒绝，草稿已保留。", "publishUnknownBody": "本次操作可能已被接收。请先查询结果，再决定是否重新发布；原始正文与作者已保留。", "publishDraftKept": "正文仍保留在草稿中。再次发布前，请重新检查正文与作者。", "publishSampleRecord": "发布记录 · 样例", "publishSampleTx": "样例 TxID", "publishSimulation": "原型演示：使用签名与交易样例，不发送真实交易，也不产生费用。", "publishQuery": "查询结果", "publishReviewAgain": "返回草稿重新检查", "publishAuthorizeTitle": "授权身份签名", "publishSampleWallet": "模拟钱包", "publishAuthorizeBody": "使用以下身份为刚才确认的 Markdown 正文签名，随后发布。", "publishAuthorize": "授权签名", "scenario-publish": "发布结果", "scenario-query": "待核实查询", "scenario-confirmation": "链上确认", "scenario-account": "发布时账户变化", "scenario-success": "成功", "scenario-sign-failed": "签名失败", "scenario-broadcast-failed": "发布拒绝", "scenario-unknown": "结果待核实", "scenario-accepted": "已接收", "scenario-not-received": "明确未接收", "scenario-pending": "确认中", "scenario-confirmed": "已确认", "scenario-none": "不触发", "scenario-broadcasting-switch": "发布中切换账户", "scenario-broadcasting-disconnect": "发布中断开连接"});
  Object.assign(words.en, {"publishStorageBefore": "The operation could not be saved, so signing has not started. Your draft is kept. Restore storage and review again."});
  Object.assign(words.zh, {"publishStorageBefore": "本次操作暂时无法保存，尚未开始签名，草稿已保留。请恢复存储后重新检查。"});
  Object.assign(words.en, {"readerPublic": "Public reading", "readerMissing": "This demo content was not found", "readerMissingBody": "This link may point to content created in another browser. Demo publications are stored only in the browser that created them. You can read a built-in sample instead.", "readerCopyLink": "Copy link", "readerVersion": "Version", "readerLocalScope": "Demo publication: built-in samples are shareable. New demo content can be reopened in this browser; it is not retrieved from a live chain."});
  Object.assign(words.zh, {"readerPublic": "公开阅读", "readerMissing": "未找到此演示内容", "readerMissingBody": "此链接可能来自另一浏览器。新发布的演示内容只保存在发布时使用的浏览器中，你也可以阅读内置样例。", "readerCopyLink": "复制链接", "readerVersion": "版本", "readerLocalScope": "演示内容：内置样例可分享；新发布的内容可在当前浏览器重开，未连接真实链上查询。"});
  Object.assign(words.en, {"versionHistory": "Version history", "versionHistorical": "Reading an earlier version", "versionLatest": "Read latest version", "versionCurrent": "Latest", "revisionContinue": "Continue revision", "revisionCreate": "Create revision", "revisionUnchanged": "There are no changes yet. Edit the text before reviewing this revision.", "reviewOutdated": "A newer version exists. Open the latest version to start a revision.", "historyBack": "Back to reading", "versionHistoryBody": "Each publication keeps its own words. Earlier versions remain readable."});
  Object.assign(words.zh, {"versionHistory": "版本历史", "versionHistorical": "正在阅读历史版本", "versionLatest": "查看最新版本", "versionCurrent": "最新", "revisionContinue": "继续修订", "revisionCreate": "创建修订", "revisionUnchanged": "暂无修改。请修改正文后再检查发布。", "reviewOutdated": "已有更新版本，请查看最新版本后创建修订。", "historyBack": "返回阅读", "versionHistoryBody": "每次发布保留独立正文，旧版本仍可阅读。"});
  Object.assign(words.en, {"proofSummary": "Signature and chain record", "proofSimulation": "Sample evidence for this prototype. No cryptographic verification or live chain query is performed.", "proofSignature": "Content signature", "proof-valid": "Valid · sample", "proof-unverified": "Not verified", "proof-failed": "Verification failed", "proofConfirmation": "Chain confirmation", "proofSource": "Query sample source", "proofLocalSource": "Publication simulated in this browser", "proofFixtureSource": "Built-in public sample", "proofFailedBody": "The signature sample does not match. Do not treat this text as verified.", "proofUnverifiedBody": "No verified signature result is available for this sample.", "scenario-proof": "Proof signature sample", "scenario-proofConfirmation": "Proof confirmation sample", "scenario-record": "Use this record", "scenario-valid": "Valid sample", "scenario-unverified": "Not verified", "scenario-failed": "Signature mismatch"});
  Object.assign(words.zh, {"proofSummary": "签名与链上记录", "proofSimulation": "以下为原型证据样例，未执行真实密码学验证或链上查询。", "proofSignature": "内容签名", "proof-valid": "有效 · 样例", "proof-unverified": "未验证", "proof-failed": "验证失败", "proofConfirmation": "链上确认", "proofSource": "查询样例来源", "proofLocalSource": "当前浏览器的发布演示", "proofFixtureSource": "内置公开样例", "proofFailedBody": "签名样例不匹配，不能将此正文视为已验证。", "proofUnverifiedBody": "当前样例暂无已验证的签名结果。", "scenario-proof": "Proof 签名样例", "scenario-proofConfirmation": "Proof 确认样例", "scenario-record": "沿用当前记录", "scenario-valid": "有效样例", "scenario-unverified": "未验证", "scenario-failed": "签名不匹配"});
  Object.assign(words.en, {"writerTitle-checking": "Opening your workspace", "writerBody-checking": "Checking which page is editing your content.", "writerTitle-busy": "Your workspace is open in another tab", "writerBody-busy": "Continue editing there, or close that tab and retry here. This keeps your drafts and publication records from replacing each other.", "writerTitle-unavailable": "This page is available for reading", "writerBody-unavailable": "Editing needs a browser that supports coordinating tabs. Open this prototype on localhost or HTTPS in a current browser, then retry."});
  Object.assign(words.zh, {"writerTitle-checking": "正在打开内容工作区", "writerBody-checking": "正在检查当前编辑页面。", "writerTitle-busy": "内容工作区已在另一页打开", "writerBody-busy": "请在原页面继续编辑，或关闭原页面后在此重试，避免草稿和发布记录相互覆盖。", "writerTitle-unavailable": "当前页面可供阅读", "writerBody-unavailable": "编辑需要浏览器支持页面协作。请使用新版浏览器，通过 localhost 或 HTTPS 打开原型后重试。"});
  Object.assign(words.en, {"draftRecovered": "Recovered draft", "draftRecoveredBody": "Your unsaved words are in recovered drafts. Open each draft to check that it saves."});
  Object.assign(words.zh, {"draftRecovered": "恢复草稿", "draftRecoveredBody": "未保存文字已保留在恢复草稿中。请打开草稿，确认保存状态。"});
  const api = {en: words.en, zh: words.zh, locales: ['en', 'zh'], keys: Object.keys(words.en)};
  if (typeof module !== 'undefined') module.exports = api;
  else root.OwnwordCopy = api;
})(typeof window !== 'undefined' ? window : globalThis);
