/* Prototype copy dictionary. Terminology authority: _task/system-design/spec/核心认知.md §2. */
(function (root) {
  const words = {
  en: {
    flipToBack: 'Flip card', flipToFront: 'Back to front',
    viewChainRecord: 'View chain record', hideChainRecord: 'Hide chain record',
    viewFullProfile: 'View full profile', hideFullProfile: 'Hide full profile',
    connect: 'Connect Wallet', connected: 'Connected', notConnected: 'Not connected', connecting: 'Connecting', disconnect: 'Disconnect', accountSwitch: 'Switch account', wallet: 'Wallet',
    myIdentity: 'My Identity', publicIdentity: 'Public Identity', preferences: 'Preferences', theme: 'Theme', light: 'Light', dark: 'Dark', language: 'Language',
    headlineOne: 'Own your identity.', headlineTwo: 'Own your words.', welcomeIntro: 'A place to stand. A voice that belongs to you.', welcomeBody: 'Start with your wallet. Your identity and your words stay yours.',
    welcomeNote: 'Your wallet controls your identity.', horizonCaption: 'A foundation for your voice', domeLabel: 'Play the seven sky lines',
    walletNote: 'Yours Wallet', independent: 'Your identity starts with you.', footer: 'Your wallet. Your identity. Your words.', prototype: 'Interactive prototype', scenarios: 'Explore scenarios', close: 'Close',
    scenario: 'Wallet identity', new: 'New identity', existing: 'Published identity', incomplete: 'Incomplete profile', resolveFail: 'Resolution fails', missing: 'Wallet unavailable',
    simulatorNote: 'Demo only. No wallet connection, signature or transaction is sent.', simulatorHint: 'Choose an identity scenario, then connect or resolve again.',
    sampleDataNote: 'Identity and chain records are sample data. Authorization dialogs represent the external wallet.', walletAuthorization: 'Yours Wallet · External authorization',
    nextResult: 'Next operation result', resultSuccess: 'Success', nextResultHint: 'Applies once after approving a connection, creation or update. Cancelling keeps this setting.',
    accountEvent: 'Next account event', none: 'No event', 'switch-confirm': 'Switch during authorization', 'switch-process': 'Switch during processing', 'disconnect-confirm': 'Disconnect during authorization', 'disconnect-process': 'Disconnect during processing',
    accountEventHint: 'Runs once on create or update: after 1.2s in authorization, or 0.6s in processing.',
    resolveAgain: 'Resolve again', failClipboard: 'Simulate copy failure', reset: 'Reset session',
    connectTitle: 'Connect Yours Wallet', connectBody: 'Let this app see your wallet identity. Publishing needs a separate confirmation.', approve: 'Approve', cancel: 'Cancel', simulateFailure: 'Simulate failure',
    connectCancelled: 'Connection cancelled', connectFailed: 'Connection failed', connectFailedBody: 'Your identity is unchanged. Check your wallet and try again.',
    missingTitle: 'Yours Wallet is unavailable', missingBody: 'No supported wallet was found. Open Yours Wallet, then try again.', retry: 'Try Again',
    resolving: 'Resolving your identity...', resolvingBody: 'Checking whether your wallet has a published identity.', resolveFailed: "Couldn't resolve identity", resolveFailedBody: 'Try again, or disconnect and switch to another account.',
    setup: 'Identity Setup', setupHeading: 'Make it yours.', setupBody: 'Choose how your identity appears to the world.', complete: 'Complete your profile', completeBody: 'Already published. Add the missing profile details to continue.',
    avatar: 'Avatar', chooseImage: 'Choose image', removeImage: 'Remove image', imageHint: 'Local PNG, JPEG or WebP. Optional.', invalidImage: 'Choose a valid PNG, JPEG or WebP image.', name: 'Name', required: 'Enter a name.', nameLong: 'Use 100 characters or fewer.', bioLong: 'Use 1000 characters or fewer.', typeRequired: 'Choose Person or Organization.',
    type: 'Type', Person: 'Person', Organization: 'Organization', bio: 'Bio', optional: 'Optional', review: 'Review', noChanges: 'No changes', back: 'Back', profile: 'Profile', editProfile: 'Edit Profile', editHeading: 'A little more you.', editBody: 'Update how you appear. Your BAP ID stays the same.',
    reviewHeading: 'This is your identity.', reviewBody: 'Review the details before confirming in your wallet.', create: 'Create Identity', createImpact: 'Your identity and profile will become public.', saveImpact: 'Your updated profile will become public. Your BAP ID will not change.', localId: 'Locally computed · not yet published', published: 'Published', controlStatement: 'Your wallet controls this identity.',
    copy: 'Copy', copied: 'Copied', copyFailed: "Couldn't copy", copyBap: 'Copy full BAP ID', noBio: 'No bio yet.',
    createTitle: 'Confirm identity creation', saveTitle: 'Confirm profile update', currentIdentity: 'Current identity',
    creating: 'Creating identity...', saving: 'Saving...', processingBody: 'Waiting for the wallet. Disconnecting or switching account cancels this operation.',
    createCancelled: 'Creation cancelled', saveCancelled: 'Saving cancelled', retained: 'Your editing values are kept. Review them and try again when ready.',
    createFailed: "Couldn't create identity", saveFailed: "Couldn't save profile", operationFailedBody: 'The operation did not complete. Your values are kept. Try again.',
    ready: 'Your identity is ready', readyBody: 'You now have a place to stand. Your wallet remains in control.', goIdentity: 'Go to My Identity', saved: 'Saved',
    identityIntro: 'A constant in a changing world.', identityBody: 'Your public identity, under your control.', owner: 'Controlled by your connected wallet', profileDetails: 'Profile details', account: 'Wallet account',
    publicIntro: 'Your identity, in the open.', publicBody: 'A public view of the identity you control.', backIdentity: 'Back to My Identity', ownedByYou: 'Identity, owned by you.',
    save: 'Save Changes', discardTitle: 'Discard unsaved changes?', discardBody: 'Changes are not saved. Keep editing, or discard them to leave.', keepEditing: 'Keep editing', discard: 'Discard changes',
    accountChanged: 'Account changed. Pending operations were cancelled.', identityUnchanged: 'Your identity is unchanged.', current: 'Current', preferenceHint: 'Language and appearance stay on this device.',
    setupStep: 'Profile', reviewStep: 'Review', confirmStep: 'Confirm', doneStep: 'Ready', copyFailureOn: 'Copy failure simulation is on', privatePreview: 'Public view preview',
    walletStatus: 'Wallet status', persistFailed: 'Preferences could not be saved on this device.',
    chainRecord: 'Chain record', identityPublication: 'Identity publication', blockHeight: 'Block height', confirmation: 'Confirmation', confirmed: 'Confirmed', pendingConfirmation: 'Awaiting block confirmation', pendingBlock: 'Awaiting block', publicationTx: 'Publication TxID', copyTx: 'Copy publication TxID', recordUnavailable: 'Transaction record unavailable'
  },
  zh: {
    flipToBack: '翻面', flipToFront: '翻回正面',
    viewChainRecord: '查看链上记录', hideChainRecord: '收起链上记录',
    viewFullProfile: '查看完整资料', hideFullProfile: '收起完整资料',
    connect: '连接钱包', connected: '已连接', notConnected: '未连接', connecting: '正在连接', disconnect: '断开连接', accountSwitch: '切换账户', wallet: '钱包',
    myIdentity: '我的身份', publicIdentity: '公开身份', preferences: '偏好设置', theme: '主题', light: '浅色', dark: '深色', language: '语言',
    headlineOne: '拥有你的身份。', headlineTwo: '拥有你的话语。', welcomeIntro: '立于自己的坐标，发出自己的声音。', welcomeBody: '从钱包开始。身份与话语，都由你掌控。',
    welcomeNote: '你的钱包掌控你的身份。', horizonCaption: '让话语有所立足', domeLabel: '拨动七条天幕线',
    walletNote: 'Yours Wallet', independent: '身份，由你开始。', footer: '你的钱包。你的身份。你的话语。', prototype: '交互原型', scenarios: '演练场景', close: '关闭',
    scenario: '钱包身份场景', new: '新身份', existing: '已发布身份', incomplete: '资料不完整', resolveFail: '解析失败', missing: '钱包不可用',
    simulatorNote: '仅作演示。不会连接钱包、签名或发送交易。', simulatorHint: '选择身份场景后，连接钱包或重新解析。',
    sampleDataNote: '身份与链上记录均为示例数据。授权弹窗代表外部钱包界面。', walletAuthorization: 'Yours Wallet · 外部钱包授权',
    nextResult: '下一次操作结果', resultSuccess: '成功', nextResultHint: '批准连接、创建或更新后生效一次；取消授权会保留此设置。',
    accountEvent: '下一次账户变化', none: '不触发', 'switch-confirm': '授权时切换账户', 'switch-process': '处理中切换账户', 'disconnect-confirm': '授权时断开连接', 'disconnect-process': '处理中断开连接',
    accountEventHint: '创建身份或更新资料时触发一次：授权开始 1.2 秒后，或处理开始 0.6 秒后。',
    resolveAgain: '重新解析', failClipboard: '模拟复制失败', reset: '重置会话',
    connectTitle: '连接 Yours Wallet', connectBody: '允许应用查看钱包身份；发布时另行确认。', approve: '批准', cancel: '取消', simulateFailure: '模拟失败',
    connectCancelled: '连接已取消', connectFailed: '连接失败', connectFailedBody: '身份未改变。请检查钱包后重试。',
    missingTitle: 'Yours Wallet 不可用', missingBody: '未发现支持的钱包。请打开 Yours Wallet 后重试。', retry: '重试',
    resolving: '正在解析身份…', resolvingBody: '正在查询当前钱包是否已有公开身份。', resolveFailed: '无法解析身份', resolveFailedBody: '可重试，或断开后切换其他账户。',
    setup: '设置身份', setupHeading: '让身份属于你。', setupBody: '选择你向世界展示自己的方式。', complete: '完善你的资料', completeBody: '身份已发布。补全资料后继续。',
    avatar: '头像', chooseImage: '选择图片', removeImage: '移除图片', imageHint: '本地 PNG、JPEG 或 WebP，可选。', invalidImage: '请选择有效的 PNG、JPEG 或 WebP 图片。', name: '名称', required: '请输入名称。', nameLong: '名称不能超过 100 个字符。', bioLong: '简介不能超过 1000 个字符。', typeRequired: '请选择个人或组织。',
    type: '类型', Person: '个人', Organization: '组织', bio: '简介', optional: '可选', review: '预览确认', noChanges: '暂无修改', back: '返回', profile: '资料', editProfile: '编辑资料', editHeading: '更真实地表达你。', editBody: '更新展示资料，BAP ID 保持不变。',
    reviewHeading: '这就是你的身份。', reviewBody: '核对资料后，在钱包中确认。', create: '创建身份', createImpact: '你的身份和资料将公开发布。', saveImpact: '更新后的资料将公开发布，BAP ID 保持不变。', localId: '已本地计算 · 尚未发布', published: '已发布', controlStatement: '你的钱包掌控此身份。',
    copy: '复制', copied: '已复制', copyFailed: '无法复制', copyBap: '复制完整 BAP ID', noBio: '尚未填写简介。',
    createTitle: '确认创建身份', saveTitle: '确认更新资料', currentIdentity: '当前身份',
    creating: '正在创建身份…', saving: '正在保存…', processingBody: '正在等待钱包返回。断开或切换账户会取消此操作。',
    createCancelled: '创建已取消', saveCancelled: '保存已取消', retained: '已保留填写内容。核对后可重新尝试。',
    createFailed: '无法创建身份', saveFailed: '无法保存资料', operationFailedBody: '操作未完成，已保留填写内容。请重试。',
    ready: '你的身份已就绪', readyBody: '现在，你有了自己的坐标。钱包始终由你掌控。', goIdentity: '前往我的身份', saved: '已保存',
    identityIntro: '变化之中，自有坐标。', identityBody: '你的公开身份，由你掌控。', owner: '由当前连接的钱包控制', profileDetails: '资料详情', account: '钱包账户',
    publicIntro: '让世界看到你。', publicBody: '查看你所掌控身份的公开展示。', backIdentity: '返回我的身份', ownedByYou: '身份，属于你。',
    save: '保存修改', discardTitle: '放弃未保存的修改？', discardBody: '修改未保存。继续编辑，或放弃后离开。', keepEditing: '继续编辑', discard: '放弃修改',
    accountChanged: '账户已切换，进行中的操作已取消。', identityUnchanged: '身份未改变。', current: '当前', preferenceHint: '语言与主题偏好保存在此设备。',
    setupStep: '资料', reviewStep: '核对', confirmStep: '确认', doneStep: '就绪', copyFailureOn: '已开启复制失败模拟', privatePreview: '公开展示预览',
    walletStatus: '钱包状态', persistFailed: '无法在此设备保存偏好。',
    chainRecord: '链上记录', identityPublication: '身份发布记录', blockHeight: '区块高度', confirmation: '确认状态', confirmed: '已确认', pendingConfirmation: '等待区块确认', pendingBlock: '等待入块', publicationTx: '发布交易 TxID', copyTx: '复制发布交易 TxID', recordUnavailable: '暂无交易记录'
  }
  };
  const api = {en: words.en, zh: words.zh, locales: ['en', 'zh'], keys: Object.keys(words.en)};
  if (typeof module !== 'undefined') module.exports = api;
  else root.OwnwordCopy = api;
})(typeof window !== 'undefined' ? window : globalThis);
